version: '3.4'

services:

  scheduler:
    build:
      context: ./scheduler
      dockerfile: Dockerfile.scheduler
    env_file:
      - .env
    networks:
      - survethi-net

  puppeteer:
    build:
      context: ./puppeteer
      dockerfile: Dockerfile.puppeteer
    ports:
      - 3000:3000
    env_file:
      - .env
    networks:
      - survethi-net

  tool:
    image: tool
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    networks:
      - survethi-net

networks:
  survethi-net:
    driver: bridge