-- Goro changes
UPDATE LOCATION SET LOC_ADDRESS = 'Adami Wadeissa' WHERE (LOC_CITY = 'Goro') and (LOC_ADDRESS = 'Adami Wadesa');
UPDATE PATIENT SET PAT_CITY = 'Goro' AND PAT_ADDR = 'Adami Wadesa' WHERE PAT_CITY = 'Goro' AND PAT_ADDR = 'Adami Wadeissa';
UPDATE OPD SET OPD_PAT_CITY = 'Goro' AND OPD_PAT_ADDR = 'Adami Wadesa' WHERE OPD_PAT_CITY = 'Goro' AND OPD_PAT_ADDR = 'Adami Wadeissa';

UPDATE LOCATION SET LOC_ADDRESS = 'Chancho Soyoma' WHERE (LOC_CITY = 'Goro') and (LOC_ADDRESS = 'Chancho');
UPDATE PATIENT SET PAT_CITY = 'Goro' AND PAT_ADDR = 'Chancho Soyoma' WHERE PAT_CITY = 'Goro' AND PAT_ADDR = 'Chancho';
UPDATE OPD SET OPD_PAT_CITY = 'Goro' AND OPD_PAT_ADDR = 'Chancho Soyoma' WHERE OPD_PAT_CITY = 'Goro' AND OPD_PAT_ADDR = 'Chancho';

UPDATE LOCATION SET LOC_ADDRESS = 'Dibidiba Abado' WHERE (LOC_CITY = 'Goro') and (LOC_ADDRESS = 'Didibe Abado');
UPDATE PATIENT SET PAT_CITY = 'Goro' AND PAT_ADDR = 'Dibidiba Abado' WHERE PAT_CITY = 'Goro' AND PAT_ADDR = 'Didibe Abado';
UPDATE OPD SET OPD_PAT_CITY = 'Goro' AND OPD_PAT_ADDR = 'Dibidiba Abado' WHERE OPD_PAT_CITY = 'Goro' AND OPD_PAT_ADDR = 'Didibe Abado';

UPDATE LOCATION SET LOC_ADDRESS = 'Finchir Amba' WHERE (LOC_CITY = 'Goro') and (LOC_ADDRESS = 'Finchir Ambabeissa');
UPDATE PATIENT SET PAT_CITY = 'Goro' AND PAT_ADDR = 'Finchir Amba' WHERE PAT_CITY = 'Goro' AND PAT_ADDR = 'Finchir Ambabeissa';
UPDATE OPD SET OPD_PAT_CITY = 'Goro' AND OPD_PAT_ADDR = 'Finchir Amba' WHERE OPD_PAT_CITY = 'Goro' AND OPD_PAT_ADDR = 'Finchir Ambabeissa';

UPDATE LOCATION SET LOC_ADDRESS = 'Leman Abu' WHERE (LOC_CITY = 'Goro') and (LOC_ADDRESS = 'Leimen Abu');
UPDATE PATIENT SET PAT_CITY = 'Goro' AND PAT_ADDR = 'Leman Abu' WHERE PAT_CITY = 'Goro' AND PAT_ADDR = 'Leimen Abu';
UPDATE OPD SET OPD_PAT_CITY = 'Goro' AND OPD_PAT_ADDR = 'Leman Abu' WHERE OPD_PAT_CITY = 'Goro' AND OPD_PAT_ADDR = 'Leimen Abu';

UPDATE LOCATION SET LOC_ADDRESS = 'Sinano Ameya' WHERE (LOC_CITY = 'Goro') and (LOC_ADDRESS = 'Sinano Amegna Gutei');
UPDATE PATIENT SET PAT_CITY = 'Goro' AND PAT_ADDR = 'Sinano Ameya' WHERE PAT_CITY = 'Goro' AND PAT_ADDR = 'Sinano Amegna Gutei';
UPDATE OPD SET OPD_PAT_CITY = 'Goro' AND OPD_PAT_ADDR = 'Sinano Ameya' WHERE OPD_PAT_CITY = 'Goro' AND OPD_PAT_ADDR = 'Sinano Amegna Gutei';

UPDATE LOCATION SET LOC_ADDRESS = 'Sololia Kote Abote' WHERE (LOC_CITY = 'Goro') and (LOC_ADDRESS = 'Sololia Korei Abote');
UPDATE PATIENT SET PAT_CITY = 'Goro' AND PAT_ADDR = 'Sololia Kote Abote' WHERE PAT_CITY = 'Goro' AND PAT_ADDR = 'Sololia Korei Abote';
UPDATE OPD SET OPD_PAT_CITY = 'Goro' AND OPD_PAT_ADDR = 'Sololia Kote Abote' WHERE OPD_PAT_CITY = 'Goro' AND OPD_PAT_ADDR = 'Sololia Korei Abote';

-- Wolisso Rural changes
UPDATE LOCATION SET LOC_ADDRESS = 'Chirech Wonberi' WHERE (LOC_CITY = 'Wolisso Rural') and (LOC_ADDRESS = 'Chiracha Wanbari');
UPDATE PATIENT SET PAT_CITY = 'Wolisso Rural' AND PAT_ADDR = 'Chirech Wonberi' WHERE PAT_CITY = 'Wolisso Rural' AND PAT_ADDR = 'Chiracha Wanbari';
UPDATE OPD SET OPD_PAT_CITY = 'Wolisso Rural' AND OPD_PAT_ADDR = 'Chirech Wonberi' WHERE OPD_PAT_CITY = 'Wolisso Rural' AND OPD_PAT_ADDR = 'Chiracha Wanbari';

UPDATE LOCATION SET LOC_ADDRESS = 'Dire Duleti' WHERE (LOC_CITY = 'Wolisso Rural') and (LOC_ADDRESS = 'Direi Duleti');
UPDATE PATIENT SET PAT_CITY = 'Wolisso Rural' AND PAT_ADDR = 'Dire Duleti' WHERE PAT_CITY = 'Wolisso Rural' AND PAT_ADDR = 'Direi Duleti';
UPDATE OPD SET OPD_PAT_CITY = 'Wolisso Rural' AND OPD_PAT_ADDR = 'Dire Duleti' WHERE OPD_PAT_CITY = 'Wolisso Rural' AND OPD_PAT_ADDR = 'Direi Duleti';

UPDATE LOCATION SET LOC_ADDRESS = 'Senkelei Alei Mariyam' WHERE (LOC_CITY = 'Wolisso Rural') and (LOC_ADDRESS = 'Senkele Ale Mariyam');
UPDATE PATIENT SET PAT_CITY = 'Wolisso Rural' AND PAT_ADDR = 'Senkelei Alei Mariyam' WHERE PAT_CITY = 'Wolisso Rural' AND PAT_ADDR = 'Senkele Ale Mariyam';
UPDATE OPD SET OPD_PAT_CITY = 'Wolisso Rural' AND OPD_PAT_ADDR = 'Senkelei Alei Mariyam' WHERE OPD_PAT_CITY = 'Wolisso Rural' AND OPD_PAT_ADDR = 'Senkele Ale Mariyam';

-- Wonchi Rural changes
UPDATE LOCATION SET LOC_ADDRESS = 'Azer Kereinssa' WHERE (LOC_CITY = 'Wonchi') and (LOC_ADDRESS = 'Azer');
UPDATE PATIENT SET PAT_CITY = 'Wonchi' AND PAT_ADDR = 'Azer Kereinssa' WHERE PAT_CITY = 'Wonchi' AND PAT_ADDR = 'Azer';
UPDATE OPD SET OPD_PAT_CITY = 'Wonchi' AND OPD_PAT_ADDR = 'Azer Kereinssa' WHERE OPD_PAT_CITY = 'Wonchi' AND OPD_PAT_ADDR = 'Azer';

UPDATE LOCATION SET LOC_ADDRESS = 'Chebo Sanseleti' WHERE (LOC_CITY = 'Wonchi') and (LOC_ADDRESS = 'Chebo Sansalti');
UPDATE PATIENT SET PAT_CITY = 'Wonchi' AND PAT_ADDR = 'Chebo Sanseleti' WHERE PAT_CITY = 'Wonchi' AND PAT_ADDR = 'Chebo Sansalti';
UPDATE OPD SET OPD_PAT_CITY = 'Wonchi' AND OPD_PAT_ADDR = 'Chebo Sanseleti' WHERE OPD_PAT_CITY = 'Wonchi' AND OPD_PAT_ADDR = 'Chebo Sansalti';

UPDATE LOCATION SET LOC_ADDRESS = 'Echa Dibdiba' WHERE (LOC_CITY = 'Wonchi') and (LOC_ADDRESS = 'Echa');
UPDATE PATIENT SET PAT_CITY = 'Wonchi' AND PAT_ADDR = 'Echa Dibdiba' WHERE PAT_CITY = 'Wonchi' AND PAT_ADDR = 'Echa';
UPDATE OPD SET OPD_PAT_CITY = 'Wonchi' AND OPD_PAT_ADDR = 'Echa Dibdiba' WHERE OPD_PAT_CITY = 'Wonchi' AND OPD_PAT_ADDR = 'Echa';

UPDATE LOCATION SET LOC_ADDRESS = 'Shegeg Gefere' WHERE (LOC_CITY = 'Wonchi') and (LOC_ADDRESS = 'Shegag');
UPDATE PATIENT SET PAT_CITY = 'Wonchi' AND PAT_ADDR = 'Shegeg Gefere' WHERE PAT_CITY = 'Wonchi' AND PAT_ADDR = 'Shegag';
UPDATE OPD SET OPD_PAT_CITY = 'Wonchi' AND OPD_PAT_ADDR = 'Shegeg Gefere' WHERE OPD_PAT_CITY = 'Wonchi' AND OPD_PAT_ADDR = 'Shegag';

UPDATE LOCATION SET LOC_ADDRESS = 'Weldo Talfam' WHERE (LOC_CITY = 'Wonchi') and (LOC_ADDRESS = 'Waldo Telfame');
UPDATE PATIENT SET PAT_CITY = 'Wonchi' AND PAT_ADDR = 'Weldo Talfam' WHERE PAT_CITY = 'Wonchi' AND PAT_ADDR = 'Waldo Telfame';
UPDATE OPD SET OPD_PAT_CITY = 'Wonchi' AND OPD_PAT_ADDR = 'Weldo Talfam' WHERE OPD_PAT_CITY = 'Wonchi' AND OPD_PAT_ADDR = 'Waldo Telfame';

UPDATE LOCATION SET LOC_ADDRESS = 'Worabu Massi' WHERE (LOC_CITY = 'Wonchi') and (LOC_ADDRESS = 'Worabu');
UPDATE PATIENT SET PAT_CITY = 'Wonchi' AND PAT_ADDR = 'Worabu Massi' WHERE PAT_CITY = 'Wonchi' AND PAT_ADDR = 'Worabu';
UPDATE OPD SET OPD_PAT_CITY = 'Wonchi' AND OPD_PAT_ADDR = 'Worabu Massi' WHERE OPD_PAT_CITY = 'Wonchi' AND OPD_PAT_ADDR = 'Worabu';

-- Wolisso Town changes
UPDATE LOCATION SET LOC_CITY = 'Wolisso Town' WHERE LOC_CITY = 'Wolisso town';
UPDATE PATIENT SET PAT_CITY = 'Wolisso Town' WHERE PAT_CITY = 'Wolisso town';
UPDATE OPD SET OPD_PAT_CITY = 'Wolisso Town' WHERE OPD_PAT_CITY = 'Wolisso town';

-- ADD NEW FIELDS
ALTER TABLE LOCATION 
	ADD COLUMN LOC_LAT FLOAT NULL AFTER LOC_ADDRESS,
	ADD COLUMN LOC_LONG FLOAT NULL AFTER LOC_LAT,
	ADD COLUMN LOC_GEO_POS_NAME VARCHAR(100) NULL AFTER LOC_LONG,
	ADD COLUMN LOC_REFERENCE_OTHER_NAME VARCHAR(100) NULL AFTER LOC_GEO_POS_NAME,
	ADD COLUMN LOC_DIST_ID_A FLOAT NULL AFTER LOC_REFERENCE_OTHER_NAME,
	ADD COLUMN LOC_DIST_ID_B FLOAT NULL AFTER LOC_DIST_ID_A;

-- GEO POSITIONS
UPDATE LOCATION SET LOC_LAT=8.389574722, LOC_LONG=37.77604222, LOC_GEO_POS_NAME='ABADO BUKASSA HP', LOC_REFERENCE_OTHER_NAME='WAYU HC', LOC_DIST_ID_A =37.3, LOC_DIST_ID_B =3.6 WHERE LOC_CITY='Goro' AND LOC_ADDRESS='Abado Bukassa';
UPDATE LOCATION SET LOC_LAT=8.380373333, LOC_LONG=37.87782, LOC_GEO_POS_NAME='ADAMI WEDEISSA HP', LOC_REFERENCE_OTHER_NAME='GORO HC', LOC_DIST_ID_A =25.2, LOC_DIST_ID_B =3.1 WHERE LOC_CITY='Goro' AND LOC_ADDRESS='Adami Wadeissa';
UPDATE LOCATION SET LOC_LAT=8.401630278, LOC_LONG=37.96525917, LOC_GEO_POS_NAME='BEKISSEI HP', LOC_REFERENCE_OTHER_NAME='GURURA HC', LOC_DIST_ID_A =20.4, LOC_DIST_ID_B =6.6 WHERE LOC_CITY='Goro' AND LOC_ADDRESS='Bekisei';
UPDATE LOCATION SET LOC_LAT=8.453208611, LOC_LONG=37.82582917, LOC_GEO_POS_NAME='BURKA BIDO HC e HP', LOC_REFERENCE_OTHER_NAME='BURKA BIDO', LOC_DIST_ID_A =29.9, LOC_DIST_ID_B =22.3 WHERE LOC_CITY='Goro' AND LOC_ADDRESS='Burka Bido';
UPDATE LOCATION SET LOC_LAT=8.413087222, LOC_LONG=37.90380556, LOC_GEO_POS_NAME='CHANCHO SOYOMA HP', LOC_REFERENCE_OTHER_NAME='GORO HC', LOC_DIST_ID_A =18.5, LOC_DIST_ID_B =7.5 WHERE LOC_CITY='Goro' AND LOC_ADDRESS='Chancho Soyoma';
UPDATE LOCATION SET LOC_LAT=8.471121389, LOC_LONG=37.91812778, LOC_GEO_POS_NAME='CHIRECHA TEDIRA HP', LOC_REFERENCE_OTHER_NAME='GURURA HC', LOC_DIST_ID_A =13.5, LOC_DIST_ID_B =4.7 WHERE LOC_CITY='Goro' AND LOC_ADDRESS='Chirecha tedira';
UPDATE LOCATION SET LOC_LAT=8.409656389, LOC_LONG=37.86431778, LOC_GEO_POS_NAME='DEMBEL DILDILLA HP', LOC_REFERENCE_OTHER_NAME='GORO HC', LOC_DIST_ID_A =22.9, LOC_DIST_ID_B =2.9 WHERE LOC_CITY='Goro' AND LOC_ADDRESS='Dembel Dildilla';
UPDATE LOCATION SET LOC_LAT=8.4483775, LOC_LONG=37.89775778, LOC_GEO_POS_NAME='DEMBI KONO HP', LOC_REFERENCE_OTHER_NAME='GURURA HC', LOC_DIST_ID_A =17.4, LOC_DIST_ID_B =3.6 WHERE LOC_CITY='Goro' AND LOC_ADDRESS='Dembi Kono';
UPDATE LOCATION SET LOC_LAT=8.510256389, LOC_LONG=37.83520556, LOC_GEO_POS_NAME='DIBIDIBA ABADO HP', LOC_REFERENCE_OTHER_NAME='BURKA BIDO', LOC_DIST_ID_A =18.7, LOC_DIST_ID_B =11.3 WHERE LOC_CITY='Goro' AND LOC_ADDRESS='Dibidiba Abado';
UPDATE LOCATION SET LOC_LAT=8.468684167, LOC_LONG=37.86107889, LOC_GEO_POS_NAME='DOGMA DEMBI HP', LOC_REFERENCE_OTHER_NAME='BURKA BIDO', LOC_DIST_ID_A =31, LOC_DIST_ID_B =6.6 WHERE LOC_CITY='Goro' AND LOC_ADDRESS='Dogema Dembi';
UPDATE LOCATION SET LOC_LAT=8.353817222, LOC_LONG=37.79846056, LOC_GEO_POS_NAME='FINCHER AMBA HP', LOC_REFERENCE_OTHER_NAME='WAYU HC', LOC_DIST_ID_A =31.7, LOC_DIST_ID_B =3.4 WHERE LOC_CITY='Goro' AND LOC_ADDRESS='Finchir Amba';
UPDATE LOCATION SET LOC_LAT=8.426464722, LOC_LONG=37.79506389, LOC_GEO_POS_NAME='FUGO ODA MELA HP', LOC_REFERENCE_OTHER_NAME='BURKA BIDO', LOC_DIST_ID_A =32.6, LOC_DIST_ID_B =5.2 WHERE LOC_CITY='Goro' AND LOC_ADDRESS='Fugo Oda Mela';
UPDATE LOCATION SET LOC_LAT=8.378308333, LOC_LONG=37.69695278, LOC_GEO_POS_NAME='GALYIE ROGDA HP', LOC_REFERENCE_OTHER_NAME='WAYU HC', LOC_DIST_ID_A =44.4, LOC_DIST_ID_B =10.1 WHERE LOC_CITY='Goro' AND LOC_ADDRESS='Galiye Rogda';
UPDATE LOCATION SET LOC_LAT=8.384818056, LOC_LONG=37.85762806, LOC_GEO_POS_NAME='GAMBELA GORO HP', LOC_REFERENCE_OTHER_NAME='GORO HC', LOC_DIST_ID_A =23.9, LOC_DIST_ID_B =1.8 WHERE LOC_CITY='Goro' AND LOC_ADDRESS='Gambeilla Goro';
UPDATE LOCATION SET LOC_LAT=8.395551389, LOC_LONG=37.86620694, LOC_GEO_POS_NAME='GORO TOWN HP', LOC_REFERENCE_OTHER_NAME='GORO HC', LOC_DIST_ID_A =22.2, LOC_DIST_ID_B =0 WHERE LOC_CITY='Goro' AND LOC_ADDRESS='Goro Town';
UPDATE LOCATION SET LOC_LAT=8.440899167, LOC_LONG=37.92331028, LOC_GEO_POS_NAME='GURURA TOWN HP', LOC_REFERENCE_OTHER_NAME='GURURA HC', LOC_DIST_ID_A =13.8, LOC_DIST_ID_B =0 WHERE LOC_CITY='Goro' AND LOC_ADDRESS='Gurura town';
UPDATE LOCATION SET LOC_LAT=8.449860833, LOC_LONG=37.84573917, LOC_GEO_POS_NAME='KEINTEIRO BIDO HP', LOC_REFERENCE_OTHER_NAME='GORO HC', LOC_DIST_ID_A =27.9, LOC_DIST_ID_B =7.9 WHERE LOC_CITY='Goro' AND LOC_ADDRESS='Keinteiro Bido';
UPDATE LOCATION SET LOC_LAT=8.429793333, LOC_LONG=37.95468333, LOC_GEO_POS_NAME='LEMAN ABU HP', LOC_REFERENCE_OTHER_NAME='GURURA HC', LOC_DIST_ID_A =15.9, LOC_DIST_ID_B =4.1 WHERE LOC_CITY='Goro' AND LOC_ADDRESS='Leman Abu';
UPDATE LOCATION SET LOC_LAT=8.462059167, LOC_LONG=37.81009083, LOC_GEO_POS_NAME='SINANO AMEYA HP', LOC_REFERENCE_OTHER_NAME='BURKA BIDO', LOC_DIST_ID_A =32, LOC_DIST_ID_B =2.3 WHERE LOC_CITY='Goro' AND LOC_ADDRESS='Sinano Ameya';
UPDATE LOCATION SET LOC_LAT=8.420137778, LOC_LONG=37.97534333, LOC_GEO_POS_NAME='SOLOLIA KOTE ABOTEI HP', LOC_REFERENCE_OTHER_NAME='GURURA HC', LOC_DIST_ID_A =18, LOC_DIST_ID_B =7.1 WHERE LOC_CITY='Goro' AND LOC_ADDRESS='Sololia Kote Abote';
UPDATE LOCATION SET LOC_LAT=8.373044444, LOC_LONG=37.76605667, LOC_GEO_POS_NAME='WAYU HP', LOC_REFERENCE_OTHER_NAME='WAYU HC', LOC_DIST_ID_A =35, LOC_DIST_ID_B =1.8 WHERE LOC_CITY='Goro' AND LOC_ADDRESS='Wayu';
UPDATE LOCATION SET LOC_LAT=8.757815, LOC_LONG=37.9867, LOC_GEO_POS_NAME='ABADO JEWE HP', LOC_REFERENCE_OTHER_NAME='DESE JEBO HC E HP', LOC_DIST_ID_A =29.9, LOC_DIST_ID_B =9 WHERE LOC_CITY='Wolisso Rural' AND LOC_ADDRESS='Abado Jewe';
UPDATE LOCATION SET LOC_LAT=8.515122222, LOC_LONG=37.89385611, LOC_GEO_POS_NAME='ABADO LEMEN HP', LOC_REFERENCE_OTHER_NAME='CHIRECHA WOMBERI HC', LOC_DIST_ID_A =11.1, LOC_DIST_ID_B =3.5 WHERE LOC_CITY='Wolisso Rural' AND LOC_ADDRESS='Abado Lemen';
UPDATE LOCATION SET LOC_LAT=8.616319722, LOC_LONG=38.03100028, LOC_GEO_POS_NAME='ADAMI GOTU HP', LOC_REFERENCE_OTHER_NAME='OBI HC', LOC_DIST_ID_A =10.2, LOC_DIST_ID_B =7.415585596 WHERE LOC_CITY='Wolisso Rural' AND LOC_ADDRESS='Adami Gotu';
UPDATE LOCATION SET LOC_LAT=8.700841667, LOC_LONG=38.07902056, LOC_GEO_POS_NAME='ALE KOYA HP', LOC_REFERENCE_OTHER_NAME='DESE JEBO HC E HP', LOC_DIST_ID_A =22.2, LOC_DIST_ID_B =16.7 WHERE LOC_CITY='Wolisso Rural' AND LOC_ADDRESS='Ale Koya';
UPDATE LOCATION SET LOC_LAT=8.556148333, LOC_LONG=38.10919333, LOC_GEO_POS_NAME='BEDA KERO HP', LOC_REFERENCE_OTHER_NAME='KARO SIMELA HC E HP', LOC_DIST_ID_A =32.2, LOC_DIST_ID_B =5.4 WHERE LOC_CITY='Wolisso Rural' AND LOC_ADDRESS='Beda Keiro';
UPDATE LOCATION SET LOC_LAT=8.529635, LOC_LONG=37.95475667, LOC_GEO_POS_NAME='BEDESA KORCHA HP', LOC_REFERENCE_OTHER_NAME='TOMBE ANCHEBI HP E HC', LOC_DIST_ID_A =3.8, LOC_DIST_ID_B =10.66071482 WHERE LOC_CITY='Wolisso Rural' AND LOC_ADDRESS='Bedeisa Koricha';
UPDATE LOCATION SET LOC_LAT=8.437435, LOC_LONG=37.99200917, LOC_GEO_POS_NAME='BIRBISA KENTERO HP', LOC_REFERENCE_OTHER_NAME='DIRE DULETI HP AND HC', LOC_DIST_ID_A =14.8, LOC_DIST_ID_B =6.7 WHERE LOC_CITY='Wolisso Rural' AND LOC_ADDRESS='Birbirsa Kenteiro';
UPDATE LOCATION SET LOC_LAT=8.46436, LOC_LONG=37.98800472, LOC_GEO_POS_NAME='BUKASA KETA HP', LOC_REFERENCE_OTHER_NAME='DIRE DULETI HP AND HC', LOC_DIST_ID_A =12.5, LOC_DIST_ID_B =3.2 WHERE LOC_CITY='Wolisso Rural' AND LOC_ADDRESS='Bukasa Keta';
UPDATE LOCATION SET LOC_LAT=8.515148333, LOC_LONG=37.87849611, LOC_GEO_POS_NAME='CHEFE MEKANA HP', LOC_REFERENCE_OTHER_NAME='CHIRECHA WOMBERI HC', LOC_DIST_ID_A =12.8, LOC_DIST_ID_B =5.2 WHERE LOC_CITY='Wolisso Rural' AND LOC_ADDRESS='Chefe Mekana';
UPDATE LOCATION SET LOC_LAT=8.4951725, LOC_LONG=37.92249389, LOC_GEO_POS_NAME='CHIRECH WOMBERI HP', LOC_REFERENCE_OTHER_NAME='CHIRECHA WOMBERI HC', LOC_DIST_ID_A =7.7, LOC_DIST_ID_B =3.8 WHERE LOC_CITY='Wolisso Rural' AND LOC_ADDRESS='Chirecha Wonberi';
UPDATE LOCATION SET LOC_LAT=8.595619444, LOC_LONG=37.99077139, LOC_GEO_POS_NAME='DEMBELI KETA HP', LOC_REFERENCE_OTHER_NAME='OBI HC', LOC_DIST_ID_A =6.4, LOC_DIST_ID_B =3.911459291 WHERE LOC_CITY='Wolisso Rural' AND LOC_ADDRESS='Dembali Keta';
UPDATE LOCATION SET LOC_LAT=8.432944722, LOC_LONG=38.08870861, LOC_GEO_POS_NAME='DERAREI EBICHA HP', LOC_REFERENCE_OTHER_NAME='KORKE HC', LOC_DIST_ID_A =22.3, LOC_DIST_ID_B =3.393577536 WHERE LOC_CITY='Wolisso Rural' AND LOC_ADDRESS='Derare Ebicha';
UPDATE LOCATION SET LOC_LAT=8.694801111, LOC_LONG=38.0234225, LOC_GEO_POS_NAME='DESE JEBO HC E HP', LOC_REFERENCE_OTHER_NAME='WOLISSO HO', LOC_DIST_ID_A =21, LOC_DIST_ID_B =21 WHERE LOC_CITY='Wolisso Rural' AND LOC_ADDRESS='Dese Jebo';
UPDATE LOCATION SET LOC_LAT=8.454079167, LOC_LONG=38.08122389, LOC_GEO_POS_NAME='DILDILA MANGURA HP', LOC_REFERENCE_OTHER_NAME='KORKE HC', LOC_DIST_ID_A =19.3, LOC_DIST_ID_B =0.012015073 WHERE LOC_CITY='Wolisso Rural' AND LOC_ADDRESS='Dildila Mangura';
UPDATE LOCATION SET LOC_LAT=8.641193889, LOC_LONG=38.04959361, LOC_GEO_POS_NAME='DILELA TOWN HP', LOC_REFERENCE_OTHER_NAME='DILELA HC', LOC_DIST_ID_A =13.6, LOC_DIST_ID_B =0 WHERE LOC_CITY='Wolisso Rural' AND LOC_ADDRESS='Dilela Town';
UPDATE LOCATION SET LOC_LAT=8.481503056, LOC_LONG=38.00517917, LOC_GEO_POS_NAME='DIRE DULETI HP AND HC', LOC_REFERENCE_OTHER_NAME='WOLISSO HO', LOC_DIST_ID_A =0, LOC_DIST_ID_B =12.1 WHERE LOC_CITY='Wolisso Rural' AND LOC_ADDRESS='Dire Duleti';
UPDATE LOCATION SET LOC_LAT=8.643431111, LOC_LONG=38.11859472, LOC_GEO_POS_NAME='DOYO KORA HP', LOC_REFERENCE_OTHER_NAME='DILELA HC', LOC_DIST_ID_A =21.2, LOC_DIST_ID_B =7.9 WHERE LOC_CITY='Wolisso Rural' AND LOC_ADDRESS='Doyo Kora';
UPDATE LOCATION SET LOC_LAT=8.50621, LOC_LONG=37.971665, LOC_GEO_POS_NAME='FODU GORA HP', LOC_REFERENCE_OTHER_NAME='TOMBE ANCHEBI HP E HC', LOC_DIST_ID_A =5.3, LOC_DIST_ID_B =12.14021712 WHERE LOC_CITY='Wolisso Rural' AND LOC_ADDRESS='Fodu Gora';
UPDATE LOCATION SET LOC_LAT=8.5078425, LOC_LONG=38.14178139, LOC_GEO_POS_NAME='GADU KISTANE HP', LOC_REFERENCE_OTHER_NAME='SODO GERBO CLINIC HC', LOC_DIST_ID_A =38.2, LOC_DIST_ID_B =2.2 WHERE LOC_CITY='Wolisso Rural' AND LOC_ADDRESS='Gadu Kistana';
UPDATE LOCATION SET LOC_LAT=8.475610278, LOC_LONG=37.95567, LOC_GEO_POS_NAME='GURURA BAKA HP', LOC_REFERENCE_OTHER_NAME='CHIRECHA WOMBERI HC', LOC_DIST_ID_A =8.5, LOC_DIST_ID_B =11.8 WHERE LOC_CITY='Wolisso Rural' AND LOC_ADDRESS='Gurura Baka';
UPDATE LOCATION SET LOC_LAT=8.591260556, LOC_LONG=37.96340917, LOC_GEO_POS_NAME='GUTE GODEITI HP', LOC_REFERENCE_OTHER_NAME='OBI HC', LOC_DIST_ID_A =7.8, LOC_DIST_ID_B =10.62505923 WHERE LOC_CITY='Wolisso Rural' AND LOC_ADDRESS='Gute Godeti';
UPDATE LOCATION SET LOC_LAT=8.444257778, LOC_LONG=38.15871361, LOC_GEO_POS_NAME='ILALA KERSA HP', LOC_REFERENCE_OTHER_NAME='SODO GERBO CLINIC HC', LOC_DIST_ID_A =30.2, LOC_DIST_ID_B =8.8 WHERE LOC_CITY='Wolisso Rural' AND LOC_ADDRESS='Ilala Kersa';
UPDATE LOCATION SET LOC_LAT=8.472752778, LOC_LONG=38.07690472, LOC_GEO_POS_NAME='JELISSA CHEKA HP', LOC_REFERENCE_OTHER_NAME='KORKE HC', LOC_DIST_ID_A =19, LOC_DIST_ID_B =3.694972457 WHERE LOC_CITY='Wolisso Rural' AND LOC_ADDRESS='Jelisa Cheka';
UPDATE LOCATION SET LOC_LAT=8.582948333, LOC_LONG=38.08903778, LOC_GEO_POS_NAME='KARO SIMELA HC E HP', LOC_REFERENCE_OTHER_NAME='WOLISSO HO', LOC_DIST_ID_A =22.6, LOC_DIST_ID_B =22.6 WHERE LOC_CITY='Wolisso Rural' AND LOC_ADDRESS='Karo Simela';
UPDATE LOCATION SET LOC_LAT=8.47063, LOC_LONG=38.17889667, LOC_GEO_POS_NAME='KENGERA LEBU HP', LOC_REFERENCE_OTHER_NAME='SODO GERBO CLINIC HC', LOC_DIST_ID_A =33.6, LOC_DIST_ID_B =5.6 WHERE LOC_CITY='Wolisso Rural' AND LOC_ADDRESS='Kegnera Lebu';
UPDATE LOCATION SET LOC_LAT=8.4743475, LOC_LONG=38.05614639, LOC_GEO_POS_NAME='KILE HP', LOC_REFERENCE_OTHER_NAME='KORKE HC', LOC_DIST_ID_A =16.6, LOC_DIST_ID_B =4.646162906 WHERE LOC_CITY='Wolisso Rural' AND LOC_ADDRESS='Kile';
UPDATE LOCATION SET LOC_LAT=8.4530175, LOC_LONG=38.03769167, LOC_GEO_POS_NAME='KONO LAFE ARBA HP', LOC_REFERENCE_OTHER_NAME='KORKE HC', LOC_DIST_ID_A =18.4, LOC_DIST_ID_B =6.472724833 WHERE LOC_CITY='Wolisso Rural' AND LOC_ADDRESS='Kono Lefe Arba';
UPDATE LOCATION SET LOC_LAT=8.596715278, LOC_LONG=37.84808, LOC_GEO_POS_NAME='LEMEN HC', LOC_REFERENCE_OTHER_NAME='WOLISSO HO', LOC_DIST_ID_A =20, LOC_DIST_ID_B =20 WHERE LOC_CITY='Wolisso Rural' AND LOC_ADDRESS='Leman';
UPDATE LOCATION SET LOC_LAT=8.429793333, LOC_LONG=37.95468333, LOC_GEO_POS_NAME='LEMAN ABU HP', LOC_REFERENCE_OTHER_NAME='GURURA HC', LOC_DIST_ID_A =15.9, LOC_DIST_ID_B =4.1 WHERE LOC_CITY='Wolisso Rural' AND LOC_ADDRESS='Leman Abu';
UPDATE LOCATION SET LOC_LAT=8.533585556, LOC_LONG=38.01995861, LOC_GEO_POS_NAME='LEMEN AYETU HP', LOC_REFERENCE_OTHER_NAME='TOMBE ANCHEBI HP E HC', LOC_DIST_ID_A =7.2, LOC_DIST_ID_B =2.657606763 WHERE LOC_CITY='Wolisso Rural' AND LOC_ADDRESS='Leman Ayitu';
UPDATE LOCATION SET LOC_LAT=8.650293056, LOC_LONG=38.0392375, LOC_GEO_POS_NAME='MARU BABELI HP', LOC_REFERENCE_OTHER_NAME='DILELA HC', LOC_DIST_ID_A =15.6, LOC_DIST_ID_B =2.3 WHERE LOC_CITY='Wolisso Rural' AND LOC_ADDRESS='Maru Babali';
UPDATE LOCATION SET LOC_LAT=8.600975, LOC_LONG=38.05093667, LOC_GEO_POS_NAME='MARU FAKE HP', LOC_REFERENCE_OTHER_NAME='KARO SIMELA HC E HP', LOC_DIST_ID_A =14.7, LOC_DIST_ID_B =6 WHERE LOC_CITY='Wolisso Rural' AND LOC_ADDRESS='Maru Fekei';
UPDATE LOCATION SET LOC_LAT=8.567118889, LOC_LONG=37.99096944, LOC_GEO_POS_NAME='OBI KOJI HP', LOC_REFERENCE_OTHER_NAME='OBI HC', LOC_DIST_ID_A =3, LOC_DIST_ID_B =0.00283398 WHERE LOC_CITY='Wolisso Rural' AND LOC_ADDRESS='Obi Koji';
UPDATE LOCATION SET LOC_LAT=8.674649722, LOC_LONG=38.075115, LOC_GEO_POS_NAME='SENKELEI ALEI MARIAM HP', LOC_REFERENCE_OTHER_NAME='DILELA HC', LOC_DIST_ID_A =18.7, LOC_DIST_ID_B =5.4 WHERE LOC_CITY='Wolisso Rural' AND LOC_ADDRESS='Senkelei Alei Mariyam';
UPDATE LOCATION SET LOC_LAT=8.472089167, LOC_LONG=38.13228556, LOC_GEO_POS_NAME='SODO GERBO HP', LOC_REFERENCE_OTHER_NAME='SODO GERBO CLINIC HC', LOC_DIST_ID_A =25.8, LOC_DIST_ID_B =3.2 WHERE LOC_CITY='Wolisso Rural' AND LOC_ADDRESS='Sodo Gerbo';
UPDATE LOCATION SET LOC_LAT=8.582546944, LOC_LONG=38.10624139, LOC_GEO_POS_NAME='SENBO YABETA HP', LOC_REFERENCE_OTHER_NAME='KARO SIMELA HC E HP', LOC_DIST_ID_A =26.5, LOC_DIST_ID_B =3.4 WHERE LOC_CITY='Wolisso Rural' AND LOC_ADDRESS='Sombo Yabeta';
UPDATE LOCATION SET LOC_LAT=8.543621667, LOC_LONG=38.0311325, LOC_GEO_POS_NAME='TOMBE ANCHEBI HP E HC', LOC_REFERENCE_OTHER_NAME='WOLISSO HO', LOC_DIST_ID_A =0, LOC_DIST_ID_B =6.91892446 WHERE LOC_CITY='Wolisso Rural' AND LOC_ADDRESS='Tombe Anchebi';
UPDATE LOCATION SET LOC_LAT=8.632020278, LOC_LONG=37.98100639, LOC_GEO_POS_NAME='WOLUSSOMA HP', LOC_REFERENCE_OTHER_NAME='OBI HC', LOC_DIST_ID_A =10.6, LOC_DIST_ID_B =8.193224448 WHERE LOC_CITY='Wolisso Rural' AND LOC_ADDRESS='Walu Soma';
UPDATE LOCATION SET LOC_LAT=8.615187222, LOC_LONG=38.07552417, LOC_GEO_POS_NAME='WORABU BERIYU HP', LOC_REFERENCE_OTHER_NAME='DILELA HC', LOC_DIST_ID_A =18.6, LOC_DIST_ID_B =5.3 WHERE LOC_CITY='Wolisso Rural' AND LOC_ADDRESS='Warabu Bariyu';
UPDATE LOCATION SET LOC_LAT=8.475200278, LOC_LONG=38.03876083, LOC_GEO_POS_NAME='WORANE MEGNAKO HP', LOC_REFERENCE_OTHER_NAME='DIRE DULETI HP AND HC', LOC_DIST_ID_A =13.9, LOC_DIST_ID_B =6.6 WHERE LOC_CITY='Wolisso Rural' AND LOC_ADDRESS='Waranen Megnako';
UPDATE LOCATION SET LOC_LAT=8.632020278, LOC_LONG=37.98100639, LOC_GEO_POS_NAME='WOLUSSOMA HP', LOC_REFERENCE_OTHER_NAME='OBI HC', LOC_DIST_ID_A =10.6, LOC_DIST_ID_B =8.193224448 WHERE LOC_CITY='Wolisso Rural' AND LOC_ADDRESS='Wolisoma';
UPDATE LOCATION SET LOC_LAT=8.722005556, LOC_LONG=37.92054667, LOC_GEO_POS_NAME='AZER KEREINSSA HP', LOC_REFERENCE_OTHER_NAME='DULELE HC', LOC_DIST_ID_A =24.4, LOC_DIST_ID_B =4.628560867 WHERE LOC_CITY='Wonchi' AND LOC_ADDRESS='Azer Kereinssa';
UPDATE LOCATION SET LOC_LAT=8.602463611, LOC_LONG=37.90865972, LOC_GEO_POS_NAME='BELBELA BULBULLA HP', LOC_REFERENCE_OTHER_NAME='CHITU HC', LOC_DIST_ID_A =12.9, LOC_DIST_ID_B =1.687971369 WHERE LOC_CITY='Wonchi' AND LOC_ADDRESS='Belbela Bulbula';
UPDATE LOCATION SET LOC_LAT=8.736791667, LOC_LONG=37.84651028, LOC_GEO_POS_NAME='CHEBO SENSELETI HP', LOC_REFERENCE_OTHER_NAME='SELAM GATIRO HC', LOC_DIST_ID_A =32.2, LOC_DIST_ID_B =2.7 WHERE LOC_CITY='Wonchi' AND LOC_ADDRESS='Chebo Sanseleti';
UPDATE LOCATION SET LOC_LAT=8.605756667, LOC_LONG=37.92071722, LOC_GEO_POS_NAME='CHITU TOWN HP', LOC_REFERENCE_OTHER_NAME='CHITU HC', LOC_DIST_ID_A =11.3, LOC_DIST_ID_B =0.011614935 WHERE LOC_CITY='Wonchi' AND LOC_ADDRESS='Chitu Town';
UPDATE LOCATION SET LOC_LAT=8.674339167, LOC_LONG=37.95906917, LOC_GEO_POS_NAME='DAE WONDIMTU HP', LOC_REFERENCE_OTHER_NAME='DULELE HC', LOC_DIST_ID_A =18.3, LOC_DIST_ID_B =2.904894617 WHERE LOC_CITY='Wonchi' AND LOC_ADDRESS='Dae Wendimtu';
UPDATE LOCATION SET LOC_LAT=8.727942778, LOC_LONG=37.95475056, LOC_GEO_POS_NAME='DAMU DEGELEI HP', LOC_REFERENCE_OTHER_NAME='DULELE HC', LOC_DIST_ID_A =24.4, LOC_DIST_ID_B =4.651577617 WHERE LOC_CITY='Wonchi' AND LOC_ADDRESS='Damu Degelei';
UPDATE LOCATION SET LOC_LAT=8.563362778, LOC_LONG=37.83510167, LOC_GEO_POS_NAME='DEGOYE GALYE HP', LOC_REFERENCE_OTHER_NAME='LEMEN HC', LOC_DIST_ID_A =23.7, LOC_DIST_ID_B =3.5 WHERE LOC_CITY='Wonchi' AND LOC_ADDRESS='Degoye Galiye';
UPDATE LOCATION SET LOC_LAT=8.609610278, LOC_LONG=37.87893917, LOC_GEO_POS_NAME='DIMTU GODETI HP', LOC_REFERENCE_OTHER_NAME='CHITU HC', LOC_DIST_ID_A =17.1, LOC_DIST_ID_B =5.911186061 WHERE LOC_CITY='Wonchi' AND LOC_ADDRESS='Dimtu Godeti';
UPDATE LOCATION SET LOC_LAT=8.637990278, LOC_LONG=37.85685, LOC_GEO_POS_NAME='DULELE BILACHA HP', LOC_REFERENCE_OTHER_NAME='LEMEN HC', LOC_DIST_ID_A =21.5, LOC_DIST_ID_B =5 WHERE LOC_CITY='Wonchi' AND LOC_ADDRESS='Dulelei Bilacha';
UPDATE LOCATION SET LOC_LAT=8.691775833, LOC_LONG=37.94468889, LOC_GEO_POS_NAME='DULELE KORI HP', LOC_REFERENCE_OTHER_NAME='DULELE HC', LOC_DIST_ID_A =19.8, LOC_DIST_ID_B =0.012262429 WHERE LOC_CITY='Wonchi' AND LOC_ADDRESS='Dulelei kori';
UPDATE LOCATION SET LOC_LAT=8.533165278, LOC_LONG=37.84948333, LOC_GEO_POS_NAME='ECHA DIBDIBA HP', LOC_REFERENCE_OTHER_NAME='LEMEN HC', LOC_DIST_ID_A =23.9, LOC_DIST_ID_B =6.5 WHERE LOC_CITY='Wonchi' AND LOC_ADDRESS='Echa Dibdiba';
UPDATE LOCATION SET LOC_LAT=8.682828611, LOC_LONG=37.89162056, LOC_GEO_POS_NAME='FITE WATO HP', LOC_REFERENCE_OTHER_NAME='DARIYA HC', LOC_DIST_ID_A =22.4, LOC_DIST_ID_B =1.9 WHERE LOC_CITY='Wonchi' AND LOC_ADDRESS='Fite wato';
UPDATE LOCATION SET LOC_LAT=8.626495556, LOC_LONG=37.90471361, LOC_GEO_POS_NAME='HARO BESEKA HP', LOC_REFERENCE_OTHER_NAME='CHITU HC', LOC_DIST_ID_A =14.8, LOC_DIST_ID_B =4.390065805 WHERE LOC_CITY='Wonchi' AND LOC_ADDRESS='Haro Beseka';
UPDATE LOCATION SET LOC_LAT=8.554359167, LOC_LONG=37.85931417, LOC_GEO_POS_NAME='HARO KONO HP', LOC_REFERENCE_OTHER_NAME='LEMEN HC', LOC_DIST_ID_A =22.3, LOC_DIST_ID_B =10.1 WHERE LOC_CITY='Wonchi' AND LOC_ADDRESS='Haro Kono';
UPDATE LOCATION SET LOC_LAT=8.788998611, LOC_LONG=37.87678833, LOC_GEO_POS_NAME='HARO WONCHI HP', LOC_REFERENCE_OTHER_NAME='HARO WONCHI', LOC_DIST_ID_A =36.9, LOC_DIST_ID_B =2.5 WHERE LOC_CITY='Wonchi' AND LOC_ADDRESS='Haro Wonchi';
UPDATE LOCATION SET LOC_LAT=8.679738889, LOC_LONG=37.87946111, LOC_GEO_POS_NAME='KURFO GUTE HP', LOC_REFERENCE_OTHER_NAME='DARIYA HC', LOC_DIST_ID_A =22.7, LOC_DIST_ID_B =4.4 WHERE LOC_CITY='Wonchi' AND LOC_ADDRESS='Kurfo Gutei';
UPDATE LOCATION SET LOC_LAT=8.533585556, LOC_LONG=38.01995861, LOC_GEO_POS_NAME='LEMEN AYETU HP', LOC_REFERENCE_OTHER_NAME='TOMBE ANCHEBI HP E HC', LOC_DIST_ID_A =7.2, LOC_DIST_ID_B =2.657606763 WHERE LOC_CITY='Wonchi' AND LOC_ADDRESS='Leman Ayitu';
UPDATE LOCATION SET LOC_LAT=8.587530278, LOC_LONG=37.93767528, LOC_GEO_POS_NAME='METI WALGA HP', LOC_REFERENCE_OTHER_NAME='CHITU HC', LOC_DIST_ID_A =8, LOC_DIST_ID_B =3.324723497 WHERE LOC_CITY='Wonchi' AND LOC_ADDRESS='Meiti Walga';
UPDATE LOCATION SET LOC_LAT=8.646834444, LOC_LONG=37.89999028, LOC_GEO_POS_NAME='SENKOLEI KAKEI HP', LOC_REFERENCE_OTHER_NAME='CHITU HC', LOC_DIST_ID_A =17.1, LOC_DIST_ID_B =6.767041593 WHERE LOC_CITY='Wonchi' AND LOC_ADDRESS='Senkolei Kake';
UPDATE LOCATION SET LOC_LAT=8.762608333, LOC_LONG=37.92396, LOC_GEO_POS_NAME='SHEGEG GEFERE HP', LOC_REFERENCE_OTHER_NAME='DULELE HC', LOC_DIST_ID_A =30.1, LOC_DIST_ID_B =10.36795341 WHERE LOC_CITY='Wonchi' AND LOC_ADDRESS='Shegeg Gefere';
UPDATE LOCATION SET LOC_LAT=8.738617778, LOC_LONG=37.87768917, LOC_GEO_POS_NAME='WELDO TALFAM HP', LOC_REFERENCE_OTHER_NAME='DARIYA HC', LOC_DIST_ID_A =29.9, LOC_DIST_ID_B =5.7 WHERE LOC_CITY='Wonchi' AND LOC_ADDRESS='Weldo Talfam';
UPDATE LOCATION SET LOC_LAT=8.615187222, LOC_LONG=38.07552417, LOC_GEO_POS_NAME='WORABU BERIYU HP', LOC_REFERENCE_OTHER_NAME='DILELA HC', LOC_DIST_ID_A =18.6, LOC_DIST_ID_B =5.3 WHERE LOC_CITY='Wonchi' AND LOC_ADDRESS='Werabu Bariyu';
UPDATE LOCATION SET LOC_LAT=8.706288056, LOC_LONG=37.88034722, LOC_GEO_POS_NAME='WORABU MASSI HP', LOC_REFERENCE_OTHER_NAME='DARIYA HC', LOC_DIST_ID_A =25.4, LOC_DIST_ID_B =3.5 WHERE LOC_CITY='Wonchi' AND LOC_ADDRESS='Worabu Massi';
